# -*- coding: utf-8 -*-
"""Tecnhinal1_Ong-iko.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypPxi4t0Y8LanDrZ1Rjmr1-Tgcv4JNth
"""

!pip install agentpy matplotlib

import agentpy as ap
import random
import matplotlib.pyplot as plt

# Random Walker Agent
class RandomWalker(ap.Agent):
    def setup(self):
        self.position = (
            random.randint(0, self.model.p.grid_size - 1),
            random.randint(0, self.model.p.grid_size - 1)
        )
        self.path = [self.position]

    def step(self):
        x, y = self.position

        # Move randomly: right, left, up, or down
        dx, dy = random.choice([
            (1, 0), (-1, 0), (0, 1), (0, -1)
        ])

        # Keep the agent inside the grid
        x = max(0, min(self.model.p.grid_size - 1, x + dx))
        y = max(0, min(self.model.p.grid_size - 1, y + dy))

        self.position = (x, y)
        self.path.append(self.position)


# Random Walk Model
class RandomWalkModel(ap.Model):
    def setup(self):
        self.walkers = ap.AgentList(
            self, self.p.agents, RandomWalker
        )

    def step(self):
        for agent in self.walkers:
            agent.step()


# Simulation parameters
parameters = {
    "agents": 10,
    "grid_size": 15,
    "steps": 50
}

# Create and initialize the model
model = RandomWalkModel(parameters)
model.setup()

# Run the simulation
for _ in range(parameters["steps"]):
    model.step()

# Display the paths
plt.figure(figsize=(8, 8))

for i, agent in enumerate(model.walkers):
    x = [point[0] for point in agent.path]
    y = [point[1] for point in agent.path]

    plt.plot(x, y, marker="o", markersize=3, label=f"Agent {i+1}")
    plt.scatter(x[0], y[0], marker="s", s=60)

plt.xlim(-0.5, parameters["grid_size"] - 0.5)
plt.ylim(-0.5, parameters["grid_size"] - 0.5)
plt.xticks(range(parameters["grid_size"]))
plt.yticks(range(parameters["grid_size"]))
plt.grid(True)
plt.title("Random Walk Simulation Using AgentPy")
plt.xlabel("X Position")
plt.ylabel("Y Position")
plt.legend()
plt.show()

"""Modified Code"""

import agentpy as ap
import random
import matplotlib.pyplot as plt
from collections import Counter

# ------------------------------------------
# AGENT DEFINITION
# ------------------------------------------
class RandomWalker(ap.Agent):

    def setup(self):
        size = self.model.p.grid_size

        self.position = (
            random.randint(0, size - 1),
            random.randint(0, size - 1)
        )

        # Task 1: Record the agent's path
        self.path = [self.position]

    def step(self):
        size = self.model.p.grid_size
        x, y = self.position

        # Possible movement directions
        directions = [
            (1, 0), (-1, 0), (0, 1), (0, -1)
        ]

        # Task 2: Preferred direction
        if self.model.p.movement_rule == "preferred":
            directions = [
                (1, 0), (1, 0), (1, 0),
                (-1, 0), (0, 1), (0, -1)
            ]

        random.shuffle(directions)

        # Try possible movements
        for dx, dy in directions:
            nx = max(0, min(size - 1, x + dx))
            ny = max(0, min(size - 1, y + dy))

            # Task 2: Avoid occupied positions
            if self.model.p.avoid_others:
                occupied = [
                    agent.position
                    for agent in self.model.walkers
                    if agent is not self
                ]

                if (nx, ny) in occupied:
                    continue

            self.position = (nx, ny)
            break

        # Record the new position
        self.path.append(self.position)


# ------------------------------------------
# MODEL DEFINITION
# ------------------------------------------
class RandomWalkModel(ap.Model):

    def setup(self):
        self.walkers = ap.AgentList(
            self, self.p.agents, RandomWalker
        )

    def step(self):
        for agent in self.walkers:
            agent.step()


# ------------------------------------------
# SIMULATION FUNCTION
# ------------------------------------------
def run_simulation(
    agents=5,
    grid_size=10,
    steps=20,
    movement_rule="random",
    avoid_others=False
):
    parameters = {
        "agents": agents,
        "grid_size": grid_size,
        "steps": steps,
        "movement_rule": movement_rule,
        "avoid_others": avoid_others
    }

    model = RandomWalkModel(parameters)
    model.setup()

    for _ in range(steps):
        model.step()

    return model


# ------------------------------------------
# TASK 1: TRACK AGENT PATHS
# ------------------------------------------
model = run_simulation(
    agents=5,
    grid_size=10,
    steps=20
)

plt.figure(figsize=(8, 8))

for i, agent in enumerate(model.walkers):
    x = [p[0] for p in agent.path]
    y = [p[1] for p in agent.path]

    plt.plot(x, y, marker="o", markersize=3,
             label=f"Agent {i + 1}")
    plt.scatter(x[0], y[0], marker="s", s=60)

plt.title("Task 1: Agent Paths")
plt.xlabel("X Position")
plt.ylabel("Y Position")
plt.xticks(range(10))
plt.yticks(range(10))
plt.xlim(-0.5, 9.5)
plt.ylim(-0.5, 9.5)
plt.grid(True)
plt.legend()
plt.show()


# ------------------------------------------
# TASK 2: CHANGE MOVEMENT RULES
# ------------------------------------------
avoid_model = run_simulation(
    agents=5,
    grid_size=10,
    steps=20,
    movement_rule="random",
    avoid_others=True
)

preferred_model = run_simulation(
    agents=5,
    grid_size=10,
    steps=20,
    movement_rule="preferred",
    avoid_others=False
)

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

for ax, simulation, title in [
    (axes[0], avoid_model, "Agents Avoid Each Other"),
    (axes[1], preferred_model, "Preferred Rightward Movement")
]:
    for i, agent in enumerate(simulation.walkers):
        x = [p[0] for p in agent.path]
        y = [p[1] for p in agent.path]
        ax.plot(x, y, marker="o", markersize=2,
                label=f"Agent {i + 1}")

    ax.set_title(title)
    ax.set_xlabel("X Position")
    ax.set_ylabel("Y Position")
    ax.set_xlim(-0.5, 9.5)
    ax.set_ylim(-0.5, 9.5)
    ax.set_xticks(range(10))
    ax.set_yticks(range(10))
    ax.grid(True)

plt.tight_layout()
plt.show()


# ------------------------------------------
# TASK 3: ANALYZE FINAL POSITIONS
# ------------------------------------------
print("TASK 3: FINAL AGENT POSITIONS")

final_positions = []

for i, agent in enumerate(model.walkers):
    print(f"Agent {i + 1}: {agent.position}")
    final_positions.append(agent.position)

# Count how many agents occupy each final position
position_counts = Counter(final_positions)

print("\nFinal Position Distribution:")
for position, count in sorted(position_counts.items()):
    print(f"Position {position}: {count} agent(s)")

# Plot the final positions
plt.figure(figsize=(7, 7))

x = [agent.position[0] for agent in model.walkers]
y = [agent.position[1] for agent in model.walkers]

plt.scatter(x, y, s=150)

for i, agent in enumerate(model.walkers):
    plt.annotate(
        f"A{i + 1}",
        agent.position,
        xytext=(5, 5),
        textcoords="offset points"
    )

plt.title("Task 3: Final Agent Positions")
plt.xlabel("X Position")
plt.ylabel("Y Position")
plt.xticks(range(10))
plt.yticks(range(10))
plt.xlim(-0.5, 9.5)
plt.ylim(-0.5, 9.5)
plt.grid(True)
plt.show()


# ------------------------------------------
# TASK 4: COMPARE TWO SCENARIOS
# ------------------------------------------
scenario_a = run_simulation(
    agents=5,
    grid_size=10,
    steps=20
)

scenario_b = run_simulation(
    agents=10,
    grid_size=15,
    steps=50
)

fig, axes = plt.subplots(1, 2, figsize=(13, 5))

for ax, simulation, title in [
    (axes[0], scenario_a, "Scenario A: 5 Agents, 10x10 Grid, 20 Steps"),
    (axes[1], scenario_b, "Scenario B: 10 Agents, 15x15 Grid, 50 Steps")
]:
    for agent in simulation.walkers:
        x = [p[0] for p in agent.path]
        y = [p[1] for p in agent.path]
        ax.plot(x, y, alpha=0.8)

    size = simulation.p.grid_size
    ax.set_title(title)
    ax.set_xlabel("X Position")
    ax.set_ylabel("Y Position")
    ax.set_xlim(-0.5, size - 0.5)
    ax.set_ylim(-0.5, size - 0.5)
    ax.set_xticks(range(size))
    ax.set_yticks(range(size))
    ax.grid(True)

plt.tight_layout()
plt.show()

print("TASK 4: SCENARIO COMPARISON")
print("Scenario A: 5 agents, 10x10 grid, 20 steps")
print("Scenario B: 10 agents, 15x15 grid, 50 steps")
print("Compare the number of paths, movement distance, and")
print("how widely the agents spread across each grid.")
